### ISSUE TITLE
[Bug Report] Unable to quit application

### ISSUE THREAD

**Issue by theolundqvist** [alexmercerind/media_kit#180] opened 2023-05-08 15:43 UTC
**Edit by @alexmercerind:**

Add `media_kit_native_event_loop` in your pubspec.yaml.

**Original comment:**

To create a microtask in `dispose` in which we dispose of player and controller is not sufficient. To do it this way makes the app stop responding when closed. CMD+Q triggers this every time, exit triggers this sometimes, I guess that sometimes dispose has enough time to run. I have not found a way to resolve this issue.

**Comment by birros** [comment] 2023-05-09 12:34
I can't reproduce, either with my app or `media_kit_test`, if I use `cmd` + `q` while a video is playing the app closes without any problem, in release or dev mode.

Can you share a minimal example?

**Comment by birros** [comment] 2023-05-09 14:23
Wait, sorry, I can reproduce with `media_kit_test`, it happens when the video playback is finished. I'm on it.

**Comment by birros** [comment] 2023-05-09 17:00
As suggested by @alexmercerind adding `media_kit_native_event_loop` fixes this issue.

**Comment by alexmercerind** [comment] 2023-05-09 17:08
Let's close this one as there's already a recommended solution.

**Closed by alexmercerind** 2023-05-09 17:08 UTC
Labels: r: fixed

**Comment by theolundqvist** [comment] 2023-05-09 19:23
Thanks,

Maybe this should be stated in the README.

`media_kit_native_event_loop` has `MINIMUM_TARGET=11.0`, can this be lowered?

**Comment by birros** [comment] 2023-05-09 21:42
@alexmercerind I will check if I can fix this bug without `media_kit_native_event_loop`. This may lead to more issues in the future.

**Comment by birros** [comment] 2023-05-10 12:02
@alexmercerind The following patch fixes this issue without using `media_kit_native_event_loop`, this comes from the timeout of `mpv_wait_event` being infinite in release mode.
Using the same timeout in dev and release mode seems to have few impact on the cpu when the player is idle, about +0.5% on my old Intel cpu.

Since the use of `media_kit_native_event_loop` is recommended, I think this overhead is negligible and will prevent this kind of issue from occurring again.

```diff
diff --git a/media_kit/lib/src/libmpv/core/initializer_isolate.dart b/media_kit/lib/src/libmpv/core/initializer_isolate.dart
index 1ad4fbb..d9a1208 100644
--- a/media_kit/lib/src/libmpv/core/initializer_isolate.dart
+++ b/media_kit/lib/src/libmpv/core/initializer_isolate.dart
@@ -90,9 +90,6 @@ abstract class InitializerIsolate {
     }
   }
 
-  /// Detect if app running in release mode.
-  static const _isReleaseMode = bool.fromEnvironment('dart.vm.product');
-
   /// Runs on separate isolate.
   /// Calls [MPV.mpv_create] & [MPV.mpv_initialize] to create a new [mpv_handle].
   /// Uses [MPV.mpv_wait_event] to wait for the next event & notifies through the passed [SendPort] as the argument.
@@ -161,7 +158,7 @@ abstract class InitializerIsolate {
     // Ensuring the successful sending of the last event before moving to next [MPV.mpv_wait_event].
     while (true) {
       completer = Completer();
-      final event = mpv.mpv_wait_event(handle, _isReleaseMode ? -1 : 0.1);
+      final event = mpv.mpv_wait_event(handle, 0.1);
       // Sending raw address of [mpv_event].
       port.send(event.address);
       // Ensuring that the last [mpv_event] (which is at the same address) is NOT reset to [mpv_event_id.MPV_EVENT_NONE] after next [MPV.mpv_wait_event] in the loop.
```

**Comment by alexmercerind** [comment] 2023-05-25 21:57
I published few updates. The media_kit_native_event_loop is also updated.

Your code may require few changes; the API has been improved. I guarantee this is last breaking change. Apologies.
