### ISSUE TITLE
Media_kit takes to long to dispose of mpv instances

### ISSUE THREAD

**Issue by Quackdoc** [alexmercerind/media_kit#266] opened 2023-07-03 03:58 UTC
found a small issue on windows and verified it on linux, mpv doesn't release the ram `mpv_terminate_destroy()` is called which is fine, but due to how the lock is setup the time for it takes for the lock to unlock increases seemingly linearly to an extent for every new instance created before the last instance is destroyed. (10s for the first instance, 20s, 30s) 

this means if you are flicking through and mpv is auto playing you can be waiting more then 40+ seconds for each instance to release it's memory. (reproducible on media_kit_test tabs stress test by rapidly swapping between tabs) the worst I measured was 6m to release the ram to initial ram usage after about 30s of rapidly swapping between tabs. it had gotten up to 1.2gb of ram usage.

as a aside note, I wonder if this is causing an issue with linux too. I'm now wondering if GDK isn't releasing the memory because `G_OBJECT_CLASS(video_output_parent_class)->dispose(object);` is called before `mpv_terminate_destory()?` not something I have the time to test until a later point in time.

~~optimizing the lock is needed, but either optimizing the time the lock takes until it's not noticeable, or making sure the lock doesn't take extra time per instance, either would be fine in isolation but probably both should be done if possible~~

this may be related to #263.

**Comment by alexmercerind** [comment] 2023-07-22 22:30
Closing in favor of #263; which will be kept open until next stable release.

The referenced commit will fix the issue & thus the memory release behavior.

**Closed by alexmercerind** 2023-07-22 22:30 UTC
Labels: r: fixed

**Comment by drwankingstein** [comment] 2023-07-24 03:15
Please re-open this, the issue still persists and can be replicated on the tab test downloaded from here https://github.com/alexmercerind/media_kit/actions/runs/5637133921 on both windows and linux. 

this makes applications that primarily watch short videos or applications where a user could swipe past a video nearly unusable on low ram systems since after 20 or so videos ram usage can climb really high.

**Comment by alexmercerind** [comment] 2023-07-24 03:31
> Please re-open this, the issue still persists and can be replicated on the tab test downloaded from here https://github.com/alexmercerind/media_kit/actions/runs/5637133921 on both windows and linux. 
> 
> this makes applications that primarily watch short videos or applications where a user could swipe past a video nearly unusable on low ram systems since after 20 or so videos ram usage can climb really high.

Your issue is #68 not this.

**Comment by drwankingstein** [comment] 2023-07-24 03:43
that issue seems specific to linux? I verified this behaviour on windows too

**Comment by alexmercerind** [comment] 2023-07-24 03:49
> that issue seems specific to linux? I verified this behaviour on windows too
> 
> EDIT: monitoring ram for the application has ram drop as each new one gets added
> 
> ```
> flutter: media_kit: Player.dispose: 2598758092384
> flutter: media_kit: Player.dispose: 2599285333328
> flutter: media_kit: Player.dispose: 2599285336464
> flutter: media_kit: Player.dispose: 2599345145408
> flutter: media_kit: Player.dispose: 2599345140928
> ```

The majority of memory is freed right after `Player.dispose`. Only 5MB is released upon `mpv_terminate_destroy`.

The most precise explanation can be: A previously mpv instance is only terminated once no `Player` class method is called in last 10 seconds... Sorry memory does get freed & this behavior is better than crashing your application.

**Comment by drwankingstein** [comment] 2023-07-24 03:57
as explained by OP the issue is that it is not 10s, it's that it takes longer and longer each run

```diff
diff --git a/media_kit/lib/src/player/native/player/real.dart b/media_kit/lib/src/player/native/player/real.dart
index 7d75c16..d7abadd 100644
--- a/media_kit/lib/src/player/native/player/real.dart
+++ b/media_kit/lib/src/player/native/player/real.dart
@@ -92,6 +92,8 @@ class NativePlayer extends PlatformPlayer {

       Initializer.dispose(ctx);

+      //
+      Stopwatch stopwatch = new Stopwatch()..start();
       TaskQueue.instance.add(
         () {
           bool safe = true;
@@ -102,10 +104,13 @@ class NativePlayer extends PlatformPlayer {
           if (safe) {
             mpv.mpv_terminate_destroy(ctx);
             print('media_kit: Player.dispose: ${ctx.address}');
+            print('terminate_destroy_after: ${stopwatch.elapsed}');
           }
           return safe;
         },
       );
+
+      //
     }
```

```
flutter: media_kit: Player.dispose: 2298759252256
flutter: terminate_destroy_after: 0:00:20.003949
flutter: media_kit: Player.dispose: 2298997751488
flutter: terminate_destroy_after: 0:00:29.795794
flutter: media_kit: Player.dispose: 2299001687584
flutter: terminate_destroy_after: 0:00:39.766335
flutter: media_kit: Player.dispose: 2299015405984
flutter: terminate_destroy_after: 0:00:49.732073
flutter: media_kit: Player.dispose: 2299015406880
flutter: terminate_destroy_after: 0:00:59.707014
flutter: media_kit: Player.dispose: 2299015409568
flutter: terminate_destroy_after: 0:01:09.678630
flutter: media_kit: Player.dispose: 2299015402400
flutter: terminate_destroy_after: 0:01:19.502111
flutter: media_kit: Player.dispose: 2299019902592
flutter: terminate_destroy_after: 0:01:29.444567
flutter: media_kit: Player.dispose: 2299019901248
flutter: terminate_destroy_after: 0:01:36.242731
flutter: media_kit: Player.dispose: 2299019906624
flutter: terminate_destroy_after: 0:01:45.827320
flutter: media_kit: Player.dispose: 2299599399856
flutter: terminate_destroy_after: 0:01:55.373365
flutter: media_kit: Player.dispose: 2299601750448
flutter: terminate_destroy_after: 0:02:04.935463
...
```

it gets longer and longer and longer, when testing the app Im working on it only took about 2-3min to use 2.8gbs of ram in release mode, this **WILL** cause the app to crash, well not crash, but cause windows to OOM it on systems with low ram.

**Comment by alexmercerind** [comment] 2023-07-24 03:59
> as explained by OP the issue is that it is not 10s, it's that it takes longer and longer each run
> 
> ```diff
> diff --git a/media_kit/lib/src/player/native/player/real.dart b/media_kit/lib/src/player/native/player/real.dart
> index 7d75c16..d7abadd 100644
> --- a/media_kit/lib/src/player/native/player/real.dart
> +++ b/media_kit/lib/src/player/native/player/real.dart
> @@ -92,6 +92,8 @@ class NativePlayer extends PlatformPlayer {
> 
>        Initializer.dispose(ctx);
> 
> +      //
> +      Stopwatch stopwatch = new Stopwatch()..start();
>        TaskQueue.instance.add(
>          () {
>            bool safe = true;
> @@ -102,10 +104,13 @@ class NativePlayer extends PlatformPlayer {
>            if (safe) {
>              mpv.mpv_terminate_destroy(ctx);
>              print('media_kit: Player.dispose: ${ctx.address}');
> +            print('terminate_destroy_after: ${stopwatch.elapsed}');
>            }
>            return safe;
>          },
>        );
> +
> +      //
>      }
> ```
> 
> ```
> flutter: media_kit: Player.dispose: 2298759252256
> flutter: terminate_destroy_after: 0:00:20.003949
> flutter: media_kit: Player.dispose: 2298997751488
> flutter: terminate_destroy_after: 0:00:29.795794
> flutter: media_kit: Player.dispose: 2299001687584
> flutter: terminate_destroy_after: 0:00:39.766335
> flutter: media_kit: Player.dispose: 2299015405984
> flutter: terminate_destroy_after: 0:00:49.732073
> flutter: media_kit: Player.dispose: 2299015406880
> flutter: terminate_destroy_after: 0:00:59.707014
> flutter: media_kit: Player.dispose: 2299015409568
> flutter: terminate_destroy_after: 0:01:09.678630
> flutter: media_kit: Player.dispose: 2299015402400
> flutter: terminate_destroy_after: 0:01:19.502111
> flutter: media_kit: Player.dispose: 2299019902592
> flutter: terminate_destroy_after: 0:01:29.444567
> flutter: media_kit: Player.dispose: 2299019901248
> flutter: terminate_destroy_after: 0:01:36.242731
> flutter: media_kit: Player.dispose: 2299019906624
> flutter: terminate_destroy_after: 0:01:45.827320
> flutter: media_kit: Player.dispose: 2299599399856
> flutter: terminate_destroy_after: 0:01:55.373365
> flutter: media_kit: Player.dispose: 2299601750448
> flutter: terminate_destroy_after: 0:02:04.935463
> ...
> ```
> 
> it gets longer and longer and longer, when testing the app Im working on it only took about 2-3min to use 2.8gbs of ram in release mode, this **WILL** cause the app to crash, well not crash, but cause windows to OOM it on systems with low ram.

Yeah... There's a 10 seconds gap as I said.

**Comment by alexmercerind** [comment] 2023-07-24 04:02
If your whole intention is to stress test to the limits, obviously you're gonna get high memory usage & that's how it'd work. You're working in a garbage collected programming language, the stuff is going to be freed in future.
If this was an issue, I would've been bombarded.

**Comment by drwankingstein** [comment] 2023-07-24 04:03
this is not a 10sec gap, this is +10sec per video opened before the previous was terminated. Not a single video was open before the first termination. that is 2minutes it took to dispose despite no video playing at all for the last 1 minute 50 seconds. and this scales like this, 

this is not a stress test, this is normal usage on the booru app, all it takes is skipping 2-4 videos, after that if you keep using it, it will just endlessly get worse and worse

**Comment by alexmercerind** [comment] 2023-07-24 04:04
You can just read the implementation to understand the 10 seconds gap. I can't help more, sorry.

**Comment by drwankingstein** [comment] 2023-07-24 04:10
understood, seems like media_kit wont possible for my project, sorry for wasting your time here

**Comment by alexmercerind** [comment] 2023-07-25 06:26
@Quackdoc 
@drwankingstein 

I spent some time yesterday & it appears that delay isn't necessary after recent tweaks.

4c372fedd038ebd5525134b31473157731647498
5fd45b6becdaf7de655404a32806678542a48719

You can depend upon `media_kit` from main branch till then (other packages `media_kit_*` can be used from pub.dev).

@drwankingstein

After having a look at the project, I don't think it's necessary to create a new `Player`/`VideoController` each time you enter the screen, you can re-use already created ones. Re-writing the code & optimizing how you allocate/release resources one way or another can yield improvements in most cases.

For instance, [tabs example in the demo application](https://github.com/alexmercerind/media_kit/blob/main/media_kit_test/lib/tests/04.tabs_test.dart) was merely made to eliminate race conditions during initial-stage development, that's not how one should implement tabs with videos in actual project (who likes a black screen during scroll).
